[tool.poetry]
authors = ["Bernardo Meurer <bernardo@meurer.org>"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Quality Assurance",
    "Topic :: Text Processing :: Filters",
    "Topic :: Utilities",
]
description = "A Bash beautifier for the masses."
homepage = "https://github.com/lovesegfault/beautysh"
include = ["LICENSE"]
keywords = ["auto", "bash", "beautifier", "beautify", "script", "shell"]
license = "MIT"
name = "beautysh"
readme = "README.md"
repository = "https://github.com/lovesegfault/beautysh"
version = "6.2.1"

[tool.poetry.scripts]
beautysh = "beautysh:main"

[tool.poetry.dependencies]
colorama = "^0.4.4"
importlib-metadata = { version = ">=1.1.0,<4.3", python = "<3.8" }
python = "^3.6.2"
types-colorama = "^0.4.3"

[tool.poetry.dev-dependencies]
black = "^22.1"
flake8 = "^5.0.4"
isort = "^5.10.1"
mypy = "^0.931"
pytest = "^7.0.0"

[tool.pytest.ini_options]
addopts = "-v -Wdefault"

[tool.black]
line-length = 99

[tool.isort]
line_length = 99
multi_line_output = 3
profile = "black"
skip_glob = ["/nix/store/*", "result/*"]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry"]
